### ISSUE TITLE
Error Code : 500 on Add Student Page

### ISSUE THREAD

**Issue by ntamatta** [rohitcoder/EdVoid-Dev#22]
Request URL: https://demo.edvoid.com/request.php?m=student&t=add
Request Method: POST
Status Code: 500 
Remote Address: 104.27.146.235:443
Referrer Policy: strict-origin-when-cross-origin

**Comment by rohitcoder** [comment]
Function was undefined ``send_mail_new_student()``

Recently, we changed some part of our code, during that time we removed this function ``send_mail_new_student()``

**Comment by rohitcoder** [comment]
A fix has been released on this issue in our local dev environment.

You will see changes in the coming few days for our live environment.
